version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easy-meal
    build: 
      context: postgres/.
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7070:7070"
    command: -p 7070

  backend:
    build: 
      context: nest-js/.
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    command: npm run start:dev #:dev <- Si perdono i logs iniziali
    depends_on:
      - postgres
    environment:
      - POSTGRES_PORT=7070
      - POSTGRES_HOST=postgres

  socket:
    build: 
      context: websocket-server/.
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: npm run start:dev #:dev <- Si perdono i logs iniziali
    depends_on:
      - postgres

  frontend:
    build:
      context: next-js/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true #Fast refresh non funziona, fixare oppure togliere questa riga
      - BACKEND_HOST=backend
    command: npm run dev
    depends_on:
      - backend
      
volumes:
  postgres_data:
