import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '../components/header'
import { NotificationProvider } from '../contexts/notification_context'
import { verifySession } from '../lib/dal'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Easy Meal',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const token = cookies().get("session")?.value;
  let isAdmin = false;
  if(token != null) 
    isAdmin = (await verifySession()).role === "admin";
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider token={token}>
          <Header isLogin={token != null} isAdmin={isAdmin}/>
          {children}
        </NotificationProvider>
      </body>
    </html>
  )
}
