name: Testing-Backend
  
on: 
  push:
    branches:
      - 'develop'
      - 'P1-296-unit-test-backend'


jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 21

      - name: Install NPM dependencies
        run: npm ci
        working-directory: nest-js
          
      - name: Run tests
        run: npm run test:cov
        working-directory: nest-js

      - name: Install Coveralls
        run: |
          curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
          chmod +x /usr/local/bin/coveralls
          coveralls --version
        working-directory: nest-js

      - name: Send coverage to Coveralls
        run: coveralls report ./coverage/lcov.info -r ${{ secrets.COVERALLS_REPO_TOKEN }}
        working-directory: nest-js

      - name: Convert coverage to MD
        id: coverage
        run: |
          echo 'MD_REPORT<<EOF' >> $GITHUB_OUTPUT
          echo "### Code Coverage" >> $GITHUB_OUTPUT
          cat "./coverage/coverage.txt" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Add coverage report to the job summary
        run: |
          echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.coverage.outputs.MD_REPORT }}" >> $GITHUB_STEP_SUMMARY
          
      