name: Testing-Backend
  
on: 
  push:
    branches:
      - 'develop'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 21
          cache: npm
          cache-dependency-path: nest-js/package-lock.json

      - name: Install NPM dependencies
        run: npm ci
        working-directory: nest-js
          
      - name: Run tests
        run: npm run test:cov
        working-directory: nest-js

      # - name: Upload coverage
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage
      #     path: nest-js/coverage

      