name: Testing-Backend
  
on: 
  push:
    branches:
      - 'develop'


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 21
      - name: Test with coverage
        run: | 
          cd nest-js
          npm ci
          npm run test:cov
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: nest-js/coverage

      