name: Testing-Frontend
  
on: 
  push:
    branches:
      - 'develop'


jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 20.9.0
      - name:  
        run: | 
          cd next-js
          npm ci