name: Testing-Frontend
  
on: 
  push:
    branches:
      - 'develop'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 21
          cache: npm
          cache-dependency-path: next-js/package-lock.json

      - name:  Install NPM dependencies
        run: npm ci
        working-directory: next-js
